name: (Action) generic code lint
description: Runs the generic Github linter, to check "everything else" in the repo.

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        # Needed for PR workflows
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Lint Code
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: 'true'
        DEFAULT_BRANCH: "main"
        DISABLE_ERRORS: 'false'
        VALIDATE_BASH: 'true'
        VALIDATE_JSON: 'true'
        VALIDATE_MD: 'true'
        VALIDATE_TERRAFORM: 'true'
        VALIDATE_YAML: 'true'
