name: (Action) security check with checkov
description: Runs checkov to verify terraform code security

inputs:
  dir:
    description: 'Working directory inside the repo of the terraform code'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Checkout Repository (PR)
      uses: actions/checkout@v2
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 1
        # Needed for PR workflows
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        # ref: ${{ github.event.pull_request.ref }}

    - name: Checkout Repository (push)
      uses: actions/checkout@v2
      if: github.event_name != 'pull_request'
      with:
        fetch-depth: 1
        ref: ${{ github.event.ref }}
        # ref: ${{ github.event.base_ref }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.2.0"

    - name: Run `terraform init`
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: terraform init

    - name: Test terraform code with Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        framework: terraform
        directory: ${{ inputs.dir }}
