name: npm publish

on:
  workflow_call:

jobs:
  install:
        runs-on: self-hosted
        steps:
            - name: 'Download a single artifact'
              uses: actions/download-artifact@v3
              with:
                name: dist    
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  # registry-url: https://npm.pkg.github.com/

            - name: 'npm publish'
              run: npm release
