name: npm ci

on:
  workflow_call:

jobs:
  install:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  # registry-url: https://npm.pkg.github.com/

            - name: 'Install NPM dependencies'
              run: npm ci
