name: npm publish

on:
  workflow_call:

jobs:
  install:
        runs-on: self-hosted
        steps:
#             - name: 'Download a single artifact'
#               uses: actions/download-artifact@v3
#               with:
#                 name: dist    
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  # registry-url: https://npm.pkg.github.com/

            - name: Restore node_modules
              id: cache-node-modules
              uses: actions/cache@v2
              with:
                path: node_modules
                key: node-modules-${{ hashFiles('package-lock.json') }}                  

            - name: 'npm publish'
              run: npm run release
