name: npm ci

on:
  workflow_call:
    secrets:
      NODE_AUTH_TOKEN:
        required: false  

jobs:
  install:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  # registry-url: https://npm.pkg.github.com/

            - name: 'Install NPM dependencies'
              run: npm ci
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

            - name: Cache node_modules
              id: cache-node-modules
              uses: actions/cache@v2
              with:
                path: node_modules
                key: node-modules-${{ hashFiles('package-lock.json') }}   
