name: npm lint

on:
  workflow_call:

jobs:
  install:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  # registry-url: https://npm.pkg.github.com/

            - name: Restore node_modules
              id: cache-node-modules
              uses: actions/cache@v2
              with:
                path: node_modules
                key: node-modules-${{ hashFiles('package-lock.json') }}           

            - name: 'npm run lint'
              run: npm run lint
