name: npm build

on:
  workflow_call:

jobs:
  install:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  # registry-url: https://npm.pkg.github.com/

            - name: 'npm build'
              run: |
                npm run build
                ls -la
            - name: 'Upload Artifact'
              uses: actions/upload-artifact@v3
              with:
                name: dist
                path: ./dist                
